// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-q1A8qDQ9GLuCfqim9GL0PlRNl9Oa47Y',
    appId: '1:1041673071982:web:2a12844871190b37bf657f',
    messagingSenderId: '1041673071982',
    projectId: 'cahaya-mulya-abadi',
    authDomain: 'cahaya-mulya-abadi.firebaseapp.com',
    storageBucket: 'cahaya-mulya-abadi.firebasestorage.app',
    measurementId: 'G-WSWN985BCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRQU63r4T3QK4IOLANffH4aYBC5TKVoOk',
    appId: '1:1041673071982:android:33faf5b22407cf79bf657f',
    messagingSenderId: '1041673071982',
    projectId: 'cahaya-mulya-abadi',
    storageBucket: 'cahaya-mulya-abadi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW7wvyDxA6KCKLJENMJvJaW0PRTd3G7v8',
    appId: '1:1041673071982:ios:e1f45296e5c70062bf657f',
    messagingSenderId: '1041673071982',
    projectId: 'cahaya-mulya-abadi',
    storageBucket: 'cahaya-mulya-abadi.firebasestorage.app',
    iosBundleId: 'com.example.cahayaMulyaAbadi',
  );

}